---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Easter Week Challenge

## Rerun
~~*deleted scripts*~~, ~~completed~~, (Old Name)

* scripts
  * 1-data-prep
    * ~~Bear-Prep.R~~
    * ~~Caribou-Prep.R~~
    * ~~Coyote-Prep.R~~
    * ~~Elk-Prep.R~~
    * ~~Wolf-Prep.R~~
    * ~~Covariate-Prep-NL.R Covariate-Prep-RMNP.R (RasterPrep.R)~~
    * ~~*RuggCalc.R*~~
  * 2-rsf
    * *Generating summary tables for RSFs.R*
    * RMNP-RSF.R (*WolfRSF.R*, *ElkRSF.R*)~~
    * ~~NL-RSF.R (*CaribouRSF.R*, *CoyoteRSF.R*, *BearRSF.R*, *NLPredRSFs.R*)~~
  * 3-extraction
    * Caribou-Extraction.R (cariboudata-rsfvalues.R)
    * Elk-Extraction.R (elkdata-rsfvalues.R)
  * 4-sociality
    * Calculate-Turn-Angles.R
    * Nearest-Neighbour-Analysis.R
  * 5-model
    * sociality-domain-GLM.R
  * 0-variables
    * variables.R
```



## TODOs/NOTEs

```{bash}
grep -rni 'R/' -e 'TODO' || true;
grep -rni 'scripts/' -e 'TODO' || true;
```

## Project structure
```
.
├── graphics
│   ├── data-model-prep
│   └── data-prep
├── input
│   ├── covariates
│   │   └── RMNP
│   ├── etc
│   │   ├── NL-Bounds
│   │   └── RMNP-extent
│   └── locs
│       ├── RMNP_WolfLocations
│       ├── AllCaribouDataRaw.csv
│       ├── Bears.csv
│       ├── Coyote.csv
│    *  RMNP_ElkData_clean.csv
├── output
│   ├── angles
│   ├── data-prep
│   ├── nna
│   ├── predator-rsf
│   ├── prey-rsf
│   └── rsf-values
├── R
│   ├── 0-functions
│   │   ├── calc_abs_angle.R
│   │   ├── prep_date.R
│   │   ├── DyadicDistance.R
│   │   ├── DyadicID.R
│   │   ├── FindNumbWithinDistance.R
│   │   ├── generate_grid.R
│   │   ├── NumbQuadTreeNeighbours.R
│   │   ├── PlotLocsByFigure.R
│   │   ├── calc_rel_angle.R
│   │   ├── StepLength.R
│   │   └── TemporalDistributionFigure.R
│   ├── 0-variables
│   │   ├── CutOffThresholds.R
│   │   └── PrepDataOutputVariables.R
│   ├── 1-data-prep
│   │   ├── BearPrep.R
│   │   ├── CaribouPrep.R
│   │   ├── CoyotePrep.R
│   │   ├── ElkPrep.R
│   │   ├── RasterPrep.R
│   │   ├── RuggCalc.R
│   │   └── WolfPrep.R
│   ├── 2-rsf
│   │   ├── predator-rsf
│   │   │   ├── BearRSF2.R
│   │   │   ├── BearRSF.R
│   │   │   ├── CoyoteRSF2.R
│   │   │   ├── CoyoteRSF.R
│   │   │   └── WolfRSF.R
│   │   ├── prey-rsf
│   │   │   ├── CaribouRSF2.R
│   │   │   ├── CaribouRSF.R
│   │   │   └── ElkRSF.R
│   │   └── NLPredRSFs.R
│   ├── 3-extraction
│   │   ├── cariboudata-rsfvalues.R
│   │   └── elkdata-rsfvalues.R
│   ├── 4-sociality
│   │   ├── 4.1-CalculateTurnAngles.R
│   │   └── 4.2-NearestNeighbourAnalysis.R
│   ├── 5-model
│   │   └── socialitydomainGLM.R
│   └── Generating summary tables for RSFs.R
├── CONTRIBUTING.md
├── ewc.Rproj
├── LICENSE
├── NOTES.md
├── README.md
├── Spring NL Dyad Distance.jpeg
├── TODO.md
└── Winter NL DI.jpeg
```

## Output metadata

script               | output path & name            | description
---------------------|-------------------------------|--------------------
BearPrep.R           | data-prep/bear.Rds            | prepped bear data
                     |                               | 
                     |                               | 
                     |                               | 
                     |                               | 
                     |                               | 
                     |                               | 
                     |                               | 
