---
output: 
  pdf_document:
    keep_tex: false
header-includes:
  - \usepackage{booktabs}
---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
knitr::opts_knit$set(root.dir = '..')

library(knitr)
library(pander)
```

```{r packages, results = 'hide'}
library(data.table)
library(ggplot2)
```


```{r input, results = 'hide'}
coyote <- readRDS('output/1-data-prep/coyote.Rds')
caribou <- readRDS('output/1-data-prep/caribou.Rds')
bear <- readRDS('output/1-data-prep/bear.Rds')
wolf <- readRDS('output/1-data-prep/wolf.Rds')
elk <- readRDS('output/1-data-prep/elk.Rds')
```


```{r, echo = TRUE}
coyote[, .N, .(yr)]
coyote[, uniqueN(id), .(yr)]
coyote[, uniqueN(id)]
coyote[, range(yr)]
```

```{r, echo = TRUE}
elk[, .N, .(yr)]
elk[, uniqueN(id), .(yr)]
elk[, uniqueN(id)]
elk[, range(yr)]
```

```{r, echo = TRUE}
wolf[, .N, .(yr)]
wolf[, uniqueN(id), .(yr)]
wolf[, uniqueN(id)]
wolf[, range(yr)]
```

```{r, echo = TRUE}
bear[, .N, .(yr)]
bear[, uniqueN(id), .(yr)]
bear[, uniqueN(id)]
bear[, range(yr)]
```

```{r, echo = TRUE}
caribou[, .N, .(yr)]
caribou[, uniqueN(id), .(yr)]
caribou[, uniqueN(id)]
caribou[, range(yr)]
```