---
title: "Summary RSF Tables"
output: pdf_document
header-includes:
   - \usepackage{booktabs}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = '..')

library(knitr)
library(pander)
```

\clearpage

```{r packages, results = 'hide'}
library(data.table)
library(piecewiseSEM)
library(lme4)
```


```{r input}
rsfs <- data.table(
  paths = dir('output/2-rsf', '[SpringWinter]RSF.Rds', recursive = TRUE, full.names = TRUE)
)
rsfs[, species := tstrsplit(paths, '/', keep = 3)]

rsfs[grepl('Spring', paths), season := 'spring']
rsfs[grepl('Winter', paths), season := 'winter']

rsfs <- rsfs[!(season == 'winter' & species == 'bear')]
```

```{r processing}
digits <- 3
summary <- rsfs[, {
  r <- readRDS(paths)
  coefs <- coef(r)
  
  se <- sqrt(diag(vcov(r)))
  
  lci <- coefs - (se * 1.96)
  uci <- coefs + (se * 1.96)
  
  
  list(Coefficient = names(coefs),
       Estimate = paste0(round(coefs, digits = digits), " [", 
                         round(lci, digits = digits), ", ",
                         round(uci, digits = digits),"]"),
       RSquared = rsquared(r)$`R.squared`,
       paths)
}, by = .(season, species)]
```

```{r models, results = 'asis'}
digits <- 3
zzz <- rsfs[, {
  r <- readRDS(paths)
  print(kable(broom::tidy(r),
              format = 'latex', 
              booktabs = TRUE))
}, by = .(season, species)]
```


```{r tables, results = 'asis'}
tabs <- summary[, {
  print(kable(broom::tidy(readRDS(paths)),
              format = 'latex', 
              booktabs = TRUE))
  
  print(kable(
    .SD,
    format = 'latex',
    booktabs = TRUE,
    linesep = '',
    caption = paste0(.BY, collapse = ' ')
    ))
}, by = .(species, season)]
```
